### ISSUE TITLE
Feature: macos support

### ISSUE THREAD

**Issue by hazcod** [liamg/memit#2]
Hi, thank you for your work!

Are there any technical reasons this wouldn't work on macOS?

**Comment by owenrumney** [comment]
+1

**Comment by liamg** [comment]
Hey @hazcod - unfortunately I’m not sure this would be possible, or at least it won’t be using the same method. It’s currently using a Linux syscall (memfd_create) to do this.

**Comment by owenrumney** [comment]
Boooooo
